index = {
"Sparse Similarity LCCI" : "sparse-similarity-lcci",
"Langtons Ant LCCI" : "langtons-ant-lcci",
"Word Rectangle LCCI" : "word-rectangle-lcci",
"Sum Swap LCCI" : "sum-swap-lcci",
"T9 LCCI" : "t9-lcci",
"Max Submatrix LCCI" : "max-submatrix-lcci",
"Max Black Square LCCI" : "max-black-square-lcci",
"Missing Two LCCI" : "missing-two-lcci",
"Shortest Supersequence LCCI" : "shortest-supersequence-lcci",
"Pairs With Sum LCCI" : "pairs-with-sum-lcci",
"Rank from Stream LCCI" : "rank-from-stream-lcci",
"Group Anagrams LCCI" : "group-anagrams-lcci",
"Find Closest LCCI" : "find-closest-lcci",
"Find Majority Element LCCI" : "find-majority-element-lcci",
"Get Kth Magic Number LCCI" : "get-kth-magic-number-lcci",
"Circus Tower LCCI" : "circus-tower-lcci",
"Baby Names LCCI" : "baby-names-lcci",
"Number Of 2s In Range LCCI" : "number-of-2s-in-range-lcci",
"Find Longest Subarray LCCI" : "find-longest-subarray-lcci",
"Missing Number LCCI" : "missing-number-lcci",
"Boolean Evaluation LCCI" : "boolean-evaluation-lcci",
"Word Transformer LCCI" : "word-transformer-lcci",
"Volume of Histogram LCCI" : "volume-of-histogram-lcci",
"Continuous Median LCCI" : "continuous-median-lcci",
"Calculator LCCI" : "calculator-lcci",
"LRU Cache LCCI" : "lru-cache-lcci",
"Add Without Plus LCCI" : "add-without-plus-lcci",
"Multi Search LCCI" : "multi-search-lcci",
"The Masseuse LCCI" : "the-masseuse-lcci",
"Longest Word LCCI" : "longest-word-lcci",
"Smallest K LCCI" : "smallest-k-lcci",
"Re-Space LCCI" : "re-space-lcci",
"BiNode LCCI" : "binode-lcci",
"English Int LCCI" : "english-int-lcci",
"Factorial Zeros LCCI" : "factorial-zeros-lcci",
"Sorted Matrix Search LCCI" : "sorted-matrix-search-lcci",
"Hanota LCCI" : "hanota-lcci",
"Peaks and Valleys LCCI" : "peaks-and-valleys-lcci",
"Sorted Merge LCCI" : "sorted-merge-lcci",
"Robot in a Grid LCCI" : "robot-in-a-grid-lcci",
"BST Sequences LCCI" : "bst-sequences-lcci",
"Paths with Sum LCCI" : "paths-with-sum-lcci",
"Partition List LCCI" : "partition-list-lcci",
"Kth Node From End of List LCCI" : "kth-node-from-end-of-list-lcci",
"One Away LCCI" : "one-away-lcci",
"Pond Sizes LCCI" : "pond-sizes-lcci",
"Pattern Matching LCCI" : "pattern-matching-lcci",
"Contiguous Sequence LCCI" : "contiguous-sequence-lcci",
"Sub Sort LCCI" : "sub-sort-lcci",
"Master Mind LCCI" : "master-mind-lcci",
"Best Line LCCI" : "best-line-lcci",
"Bisect Squares LCCI" : "bisect-squares-lcci",
"Diving Board LCCI" : "diving-board-lcci",
"Living People LCCI" : "living-people-lcci",
"Operations LCCI" : "operations-lcci",
"Maximum LCCI" : "maximum-lcci",
"Permutation II LCCI" : "permutation-ii-lcci",
"二叉树的最近公共祖先 LCOF" : "er-cha-shu-de-zui-jin-gong-gong-zu-xian-lcof",
"二叉搜索树的最近公共祖先 LCOF" : "er-cha-sou-suo-shu-de-zui-jin-gong-gong-zu-xian-lcof",
"求1+2+…+n LCOF" : "qiu-12n-lcof",
"股票的最大利润  LCOF" : "gu-piao-de-zui-da-li-run-lcof",
"圆圈中最后剩下的数字 LCOF" : "yuan-quan-zhong-zui-hou-sheng-xia-de-shu-zi-lcof",
"平衡二叉树 LCOF" : "ping-heng-er-cha-shu-lcof",
"扑克牌中的顺子  LCOF" : "bu-ke-pai-zhong-de-shun-zi-lcof",
"把字符串转换成整数 LCOF" : "ba-zi-fu-chuan-zhuan-huan-cheng-zheng-shu-lcof",
"n个骰子的点数  LCOF" : "nge-tou-zi-de-dian-shu-lcof",
"构建乘积数组 LCOF" : "gou-jian-cheng-ji-shu-zu-lcof",
"队列的最大值 LCOF" : "dui-lie-de-zui-da-zhi-lcof",
"滑动窗口的最大值 LCOF" : "hua-dong-chuang-kou-de-zui-da-zhi-lcof",
"不用加减乘除做加法 LCOF" : "bu-yong-jia-jian-cheng-chu-zuo-jia-fa-lcof",
"丑数 LCOF" : "chou-shu-lcof",
"二叉搜索树的第k大节点  LCOF" : "er-cha-sou-suo-shu-de-di-kda-jie-dian-lcof",
"最长不含重复字符的子字符串 LCOF" : "zui-chang-bu-han-zhong-fu-zi-fu-de-zi-zi-fu-chuan-lcof",
"缺失的数字  LCOF" : "que-shi-de-shu-zi-lcof",
"左旋转字符串 LCOF" : "zuo-xuan-zhuan-zi-fu-chuan-lcof",
"在排序数组中查找数字  LCOF" : "zai-pai-xu-shu-zu-zhong-cha-zhao-shu-zi-lcof",
"翻转单词顺序 LCOF" : "fan-zhuan-dan-ci-shun-xu-lcof",
"礼物的最大价值 LCOF" : "li-wu-de-zui-da-jie-zhi-lcof",
"两个链表的第一个公共节点  LCOF" : "liang-ge-lian-biao-de-di-yi-ge-gong-gong-jie-dian-lcof",
"把数字翻译成字符串 LCOF" : "ba-shu-zi-fan-yi-cheng-zi-fu-chuan-lcof",
"和为s的连续正数序列 LCOF" : "he-wei-sde-lian-xu-zheng-shu-xu-lie-lcof",
"把数组排成最小的数 LCOF" : "ba-shu-zu-pai-cheng-zui-xiao-de-shu-lcof",
"和为s的两个数字 LCOF" : "he-wei-sde-liang-ge-shu-zi-lcof",
"数组中数字出现的次数 II LCOF" : "shu-zu-zhong-shu-zi-chu-xian-de-ci-shu-ii-lcof",
"数组中数字出现的次数 LCOF" : "shu-zu-zhong-shu-zi-chu-xian-de-ci-shu-lcof",
"二叉树的深度 LCOF" : "er-cha-shu-de-shen-du-lcof",
"数组中的逆序对  LCOF" : "shu-zu-zhong-de-ni-xu-dui-lcof",
"二叉树中和为某一值的路径 LCOF" : "er-cha-shu-zhong-he-wei-mou-yi-zhi-de-lu-jing-lcof",
"第一个只出现一次的字符  LCOF" : "di-yi-ge-zhi-chu-xian-yi-ci-de-zi-fu-lcof",
"二叉搜索树的后序遍历序列 LCOF" : "er-cha-sou-suo-shu-de-hou-xu-bian-li-xu-lie-lcof",
"从上到下打印二叉树 III LCOF" : "cong-shang-dao-xia-da-yin-er-cha-shu-iii-lcof",
"数字序列中某一位的数字  LCOF" : "shu-zi-xu-lie-zhong-mou-yi-wei-de-shu-zi-lcof",
"从上到下打印二叉树 II LCOF" : "cong-shang-dao-xia-da-yin-er-cha-shu-ii-lcof",
"从上到下打印二叉树 LCOF" : "cong-shang-dao-xia-da-yin-er-cha-shu-lcof",
"数组中出现次数超过一半的数字  LCOF" : "shu-zu-zhong-chu-xian-ci-shu-chao-guo-yi-ban-de-shu-zi-lcof",
"1～n整数中1出现的次数  LCOF" : "1nzheng-shu-zhong-1chu-xian-de-ci-shu-lcof",
"字符串的排列  LCOF" : "zi-fu-chuan-de-pai-lie-lcof",
"序列化二叉树  LCOF" : "xu-lie-hua-er-cha-shu-lcof",
"栈的压入、弹出序列 LCOF" : "zhan-de-ya-ru-dan-chu-xu-lie-lcof",
"二叉搜索树与双向链表  LCOF" : "er-cha-sou-suo-shu-yu-shuang-xiang-lian-biao-lcof",
"连续子数组的最大和  LCOF" : "lian-xu-zi-shu-zu-de-zui-da-he-lcof",
"数据流中的中位数  LCOF" : "shu-ju-liu-zhong-de-zhong-wei-shu-lcof",
"包含min函数的栈 LCOF" : "bao-han-minhan-shu-de-zhan-lcof",
"最小的k个数  LCOF" : "zui-xiao-de-kge-shu-lcof",
"复杂链表的复制  LCOF" : "fu-za-lian-biao-de-fu-zhi-lcof",
"删除链表的节点 LCOF" : "shan-chu-lian-biao-de-jie-dian-lcof",
"反转链表 LCOF" : "fan-zhuan-lian-biao-lcof",
"正则表达式匹配 LCOF" : "zheng-ze-biao-da-shi-pi-pei-lcof",
"打印从1到最大的n位数 LCOF" : "da-yin-cong-1dao-zui-da-de-nwei-shu-lcof",
"数值的整数次方 LCOF" : "shu-zhi-de-zheng-shu-ci-fang-lcof",
"链表中倒数第k个节点 LCOF" : "lian-biao-zhong-dao-shu-di-kge-jie-dian-lcof",
"顺时针打印矩阵  LCOF" : "shun-shi-zhen-da-yin-ju-zhen-lcof",
"二进制中1的个数 LCOF" : "er-jin-zhi-zhong-1de-ge-shu-lcof",
"调整数组顺序使奇数位于偶数前面 LCOF" : "diao-zheng-shu-zu-shun-xu-shi-qi-shu-wei-yu-ou-shu-qian-mian-lcof",
"表示数值的字符串 LCOF" : "biao-shi-shu-zhi-de-zi-fu-chuan-lcof",
"对称的二叉树  LCOF" : "dui-cheng-de-er-cha-shu-lcof",
"二叉树的镜像  LCOF" : "er-cha-shu-de-jing-xiang-lcof",
"树的子结构  LCOF" : "shu-de-zi-jie-gou-lcof",
"合并两个排序的链表  LCOF" : "he-bing-liang-ge-pai-xu-de-lian-biao-lcof",
"剪绳子 II LCOF" : "jian-sheng-zi-ii-lcof",
"剪绳子  LCOF" : "jian-sheng-zi-lcof",
"重建二叉树 LCOF" : "zhong-jian-er-cha-shu-lcof",
"从尾到头打印链表 LCOF" : "cong-wei-dao-tou-da-yin-lian-biao-lcof",
"机器人的运动范围  LCOF" : "ji-qi-ren-de-yun-dong-fan-wei-lcof",
"替换空格 LCOF" : "ti-huan-kong-ge-lcof",
"矩阵中的路径  LCOF" : "ju-zhen-zhong-de-lu-jing-lcof",
"旋转数组的最小数字  LCOF" : "xuan-zhuan-shu-zu-de-zui-xiao-shu-zi-lcof",
"青蛙跳台阶问题  LCOF" : "qing-wa-tiao-tai-jie-wen-ti-lcof",
"二维数组中的查找 LCOF" : "er-wei-shu-zu-zhong-de-cha-zhao-lcof",
"数组中重复的数字 LCOF" : "shu-zu-zhong-zhong-fu-de-shu-zi-lcof",
"斐波那契数列  LCOF" : "fei-bo-na-qi-shu-lie-lcof",
"用两个栈实现队列 LCOF" : "yong-liang-ge-zhan-shi-xian-dui-lie-lcof",
"Smallest Difference LCCI" : "smallest-difference-lcci",
"Tic-Tac-Toe LCCI" : "tic-tac-toe-lcci",
"Intersection LCCI" : "intersection-lcci",
"Words Frequency LCCI" : "words-frequency-lcci",
"Swap Numbers LCCI" : "swap-numbers-lcci",
"Sparse Array Search LCCI" : "sparse-array-search-lcci",
"Permutation I LCCI" : "permutation-i-lcci",
"Magic Index LCCI" : "magic-index-lcci",
"Eight Queens LCCI" : "eight-queens-lcci",
"Search Rotate Array LCCI" : "search-rotate-array-lcci",
"Coin LCCI" : "coin-lcci",
"Reverse Bits LCCI" : "reverse-bits-lcci",
"Check SubTree LCCI" : "check-subtree-lcci",
"Animal Shelter LCCI" : "animal-shelter-lcci",
"Bianry Number to String LCCI" : "bianry-number-to-string-lcci",
"Pile Box LCCI" : "pile-box-lcci",
"Color Fill LCCI" : "color-fill-lcci",
"Bracket LCCI" : "bracket-lcci",
"Recursive Mulitply LCCI" : "recursive-mulitply-lcci",
"Power Set LCCI" : "power-set-lcci",
"Three Steps Problem LCCI" : "three-steps-problem-lcci",
"Draw Line LCCI" : "draw-line-lcci",
"Stack of Plates LCCI" : "stack-of-plates-lcci",
"Sum Lists LCCI" : "sum-lists-lcci",
"Delete Middle Node LCCI" : "delete-middle-node-lcci",
"Zero Matrix LCCI" : "zero-matrix-lcci",
"Rotate Matrix LCCI" : "rotate-matrix-lcci",
"Palindrome Permutation LCCI" : "palindrome-permutation-lcci",
"Closed Number LCCI" : "closed-number-lcci",
"Exchange LCCI" : "exchange-lcci",
"Convert Integer LCCI" : "convert-integer-lcci",
"Insert Into Bits LCCI" : "insert-into-bits-lcci",
"First Common Ancestor LCCI" : "first-common-ancestor-lcci",
"Successor LCCI" : "successor-lcci",
"Legal Binary Search Tree LCCI" : "legal-binary-search-tree-lcci",
"Check Balance LCCI" : "check-balance-lcci",
"List of Depth LCCI" : "list-of-depth-lcci",
"Minimum Height Tree LCCI" : "minimum-height-tree-lcci",
"Sort of Stacks LCCI" : "sort-of-stacks-lcci",
"Three in One LCCI" : "three-in-one-lcci",
"Route Between Nodes LCCI" : "route-between-nodes-lcci",
"Implement Queue using Stacks LCCI" : "implement-queue-using-stacks-lcci",
"Min Stack LCCI" : "min-stack-lcci",
"Linked List Cycle LCCI" : "linked-list-cycle-lcci",
"Intersection of Two Linked Lists LCCI" : "intersection-of-two-linked-lists-lcci",
"Palindrome Linked List LCCI" : "palindrome-linked-list-lcci",
"Remove Duplicate Node LCCI" : "remove-duplicate-node-lcci",
"String Rotation LCCI" : "string-rotation-lcci",
"Compress String LCCI" : "compress-string-lcci",
"String to URL LCCI" : "string-to-url-lcci",
"Check Permutation LCCI" : "check-permutation-lcci",
"Is Unique LCCI" : "is-unique-lcci",
"Guess Numbers" : "guess-numbers",
"Programmable Robot" : "programmable-robot",
"Coin Bonus" : "coin-bonus",
"Broken Board Dominoes" : "broken-board-dominoes",
"Deep Dark Fraction" : "deep-dark-fraction",
"Find All Good Strings" : "find-all-good-strings",
"Design Underground System" : "design-underground-system",
"Count Number of Teams" : "count-number-of-teams",
"Find Lucky Integer in an Array" : "find-lucky-integer-in-an-array",
"Longest Happy Prefix" : "longest-happy-prefix",
"Check if There is a Valid Path in a Grid" : "check-if-there-is-a-valid-path-in-a-grid",
"Create Target Array in the Given Order" : "create-target-array-in-the-given-order",
"Maximum Performance of a Team" : "maximum-performance-of-a-team",
"Find a Corresponding Node of a Binary Tree in a Clone of That Tree" : "find-a-corresponding-node-of-a-binary-tree-in-a-clone-of-that-tree",
"Design a Stack With Increment Operation" : "design-a-stack-with-increment-operation",
"Lucky Numbers in a Matrix" : "lucky-numbers-in-a-matrix",
"Frog Position After T Seconds" : "frog-position-after-t-seconds",
"Time Needed to Inform All Employees" : "time-needed-to-inform-all-employees",
"Bulb Switcher III" : "bulb-switcher-iii",
"Generate a String With Characters That Have Odd Counts" : "generate-a-string-with-characters-that-have-odd-counts",
"Pizza With 3n Slices" : "pizza-with-3n-slices",
"Sort Integers by The Power Value" : "sort-integers-by-the-power-value",
"Cinema Seat Allocation" : "cinema-seat-allocation",
"Find the Distance Value Between Two Arrays" : "find-the-distance-value-between-two-arrays",
"Minimum Cost to Make at Least One Valid Path in a Grid" : "minimum-cost-to-make-at-least-one-valid-path-in-a-grid",
"Linked List in Binary Tree" : "linked-list-in-binary-tree",
"Rank Teams by Votes" : "rank-teams-by-votes",
"How Many Numbers Are Smaller Than the Current Number" : "how-many-numbers-are-smaller-than-the-current-number",
"Construct Target Array With Multiple Sums" : "construct-target-array-with-multiple-sums",
"Maximum Number of Events That Can Be Attended" : "maximum-number-of-events-that-can-be-attended",
"Product of the Last K Numbers" : "product-of-the-last-k-numbers",
"Count Negative Numbers in a Sorted Matrix" : "count-negative-numbers-in-a-sorted-matrix",
"Maximum Sum BST in Binary Tree" : "maximum-sum-bst-in-binary-tree",
"Longest ZigZag Path in a Binary Tree" : "longest-zigzag-path-in-a-binary-tree",
"Find the Longest Substring Containing Vowels in Even Counts" : "find-the-longest-substring-containing-vowels-in-even-counts",
"Increasing Decreasing String" : "increasing-decreasing-string",
"Maximum Students Taking Exam" : "maximum-students-taking-exam",
"Tweet Counts Per Frequency" : "tweet-counts-per-frequency",
"Minimum Number of Steps to Make Two Strings Anagram" : "minimum-number-of-steps-to-make-two-strings-anagram",
"Check If N and Its Double Exist" : "check-if-n-and-its-double-exist",
"Jump Game V" : "jump-game-v",
"Maximum Product of Splitted Binary Tree" : "maximum-product-of-splitted-binary-tree",
"Reduce Array Size to The Half" : "reduce-array-size-to-the-half",
"The K Weakest Rows in a Matrix" : "the-k-weakest-rows-in-a-matrix",
"Count All Valid Pickup and Delivery Options" : "count-all-valid-pickup-and-delivery-options",
"Number of Substrings Containing All Three Characters" : "number-of-substrings-containing-all-three-characters",
"Apply Discount Every n Orders" : "apply-discount-every-n-orders",
"Sort Integers by The Number of 1 Bits" : "sort-integers-by-the-number-of-1-bits",
"Minimum Difficulty of a Job Schedule" : "minimum-difficulty-of-a-job-schedule",
"Find the City With the Smallest Number of Neighbors at a Threshold Distance" : "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance",
"Filter Restaurants by Vegan-Friendly, Price and Distance" : "filter-restaurants-by-vegan-friendly-price-and-distance",
"Remove Palindromic Subsequences" : "remove-palindromic-subsequences",
"Minimum Number of Taps to Open to Water a Garden" : "minimum-number-of-taps-to-open-to-water-a-garden",
"Delete Leaves With a Given Value" : "delete-leaves-with-a-given-value",
"Print Words Vertically" : "print-words-vertically",
"Maximum 69 Number" : "maximum-69-number",
"Jump Game IV" : "jump-game-iv",
"Angle Between Hands of a Clock" : "angle-between-hands-of-a-clock",
"Number of Sub-arrays of Size K and Average Greater than or Equal to Threshold" : "number-of-sub-arrays-of-size-k-and-average-greater-than-or-equal-to-threshold",
"Number of Steps to Reduce a Number to Zero" : "number-of-steps-to-reduce-a-number-to-zero",
"Minimum Distance to Type a Word Using Two Fingers" : "minimum-distance-to-type-a-word-using-two-fingers",
"Number of Operations to Make Network Connected" : "number-of-operations-to-make-network-connected",
"Minimum Flips to Make a OR b Equal to c" : "minimum-flips-to-make-a-or-b-equal-to-c",
"Convert Integer to the Sum of Two No-Zero Integers" : "convert-integer-to-the-sum-of-two-no-zero-integers",
"Minimum Insertion Steps to Make a String Palindrome" : "minimum-insertion-steps-to-make-a-string-palindrome",
"Get Watched Videos by Your Friends" : "get-watched-videos-by-your-friends",
"XOR Queries of a Subarray" : "xor-queries-of-a-subarray",
"Decrypt String from Alphabet to Integer Mapping" : "decrypt-string-from-alphabet-to-integer-mapping",
"Verbal Arithmetic Puzzle" : "verbal-arithmetic-puzzle",
"Jump Game III" : "jump-game-iii",
"All Elements in Two Binary Search Trees" : "all-elements-in-two-binary-search-trees",
"Find N Unique Integers Sum up to Zero" : "find-n-unique-integers-sum-up-to-zero",
"Maximum Candies You Can Get from Boxes" : "maximum-candies-you-can-get-from-boxes",
"Maximum Number of Occurrences of a Substring" : "maximum-number-of-occurrences-of-a-substring",
"Divide Array in Sets of K Consecutive Numbers" : "divide-array-in-sets-of-k-consecutive-numbers",
"Find Numbers with Even Number of Digits" : "find-numbers-with-even-number-of-digits",
"Shortest Path in a Grid with Obstacles Elimination" : "shortest-path-in-a-grid-with-obstacles-elimination",
"Maximum Side Length of a Square with Sum Less than or Equal to Threshold" : "maximum-side-length-of-a-square-with-sum-less-than-or-equal-to-threshold",
"Convert Binary Number in a Linked List to Integer" : "convert-binary-number-in-a-linked-list-to-integer",
"Minimum Number of Flips to Convert Binary Matrix to Zero Matrix" : "minimum-number-of-flips-to-convert-binary-matrix-to-zero-matrix",
"Find the Smallest Divisor Given a Threshold" : "find-the-smallest-divisor-given-a-threshold",
"Group the People Given the Group Size They Belong To" : "group-the-people-given-the-group-size-they-belong-to",
"Subtract the Product and Sum of Digits of an Integer" : "subtract-the-product-and-sum-of-digits-of-an-integer",
"Palindrome Partitioning III" : "palindrome-partitioning-iii",
"Count Square Submatrices with All Ones" : "count-square-submatrices-with-all-ones",
"Number of Burgers with No Waste of Ingredients" : "number-of-burgers-with-no-waste-of-ingredients",
"Find Winner on a Tic Tac Toe Game" : "find-winner-on-a-tic-tac-toe-game",
"Number of Ways to Stay in the Same Place After Some Steps" : "number-of-ways-to-stay-in-the-same-place-after-some-steps",
"Search Suggestions System" : "search-suggestions-system",
"Count Servers that Communicate" : "count-servers-that-communicate",
"Minimum Time Visiting All Points" : "minimum-time-visiting-all-points",
"Minimum Moves to Move a Box to Their Target Location" : "minimum-moves-to-move-a-box-to-their-target-location",
"Greatest Sum Divisible by Three" : "greatest-sum-divisible-by-three",
"Find Elements in a Contaminated Binary Tree" : "find-elements-in-a-contaminated-binary-tree",
"Shift 2D Grid" : "shift-2d-grid",
"Maximum Score Words Formed by Letters" : "maximum-score-words-formed-by-letters",
"Number of Closed Islands" : "number-of-closed-islands",
"Reconstruct a 2-Row Binary Matrix" : "reconstruct-a-2-row-binary-matrix",
"Cells with Odd Values in a Matrix" : "cells-with-odd-values-in-a-matrix",
"Check If It Is a Good Array" : "check-if-it-is-a-good-array",
"Minimum Remove to Make Valid Parentheses" : "minimum-remove-to-make-valid-parentheses",
"Count Number of Nice Subarrays" : "count-number-of-nice-subarrays",
"Minimum Swaps to Make Strings Equal" : "minimum-swaps-to-make-strings-equal",
"Airplane Seat Assignment Probability" : "airplane-seat-assignment-probability",
"Tiling a Rectangle with the Fewest Squares" : "tiling-a-rectangle-with-the-fewest-squares",
"Maximum Length of a Concatenated String with Unique Characters" : "maximum-length-of-a-concatenated-string-with-unique-characters",
"Circular Permutation in Binary Representation" : "circular-permutation-in-binary-representation",
"Find Positive Integer Solution for a Given Equation" : "find-positive-integer-solution-for-a-given-equation",
"Maximum Profit in Job Scheduling" : "maximum-profit-in-job-scheduling",
"Replace the Substring for Balanced String" : "replace-the-substring-for-balanced-string",
"Remove Sub-Folders from the Filesystem" : "remove-sub-folders-from-the-filesystem",
"Check If It Is a Straight Line" : "check-if-it-is-a-straight-line",
"Maximum Equal Frequency" : "maximum-equal-frequency",
"Dice Roll Simulation" : "dice-roll-simulation",
"Queens That Can Attack the King" : "queens-that-can-attack-the-king",
"Split a String in Balanced Strings" : "split-a-string-in-balanced-strings",
"The Dining Philosophers" : "the-dining-philosophers",
"Design Skiplist" : "design-skiplist",
"Count Vowels Permutation" : "count-vowels-permutation",
"Path with Maximum Gold" : "path-with-maximum-gold",
"Longest Arithmetic Subsequence of Given Difference" : "longest-arithmetic-subsequence-of-given-difference",
"Play with Chips" : "play-with-chips",
"Minimum Moves to Reach Target with Rotations" : "minimum-moves-to-reach-target-with-rotations",
"Get Equal Substrings Within Budget" : "get-equal-substrings-within-budget",
"Remove All Adjacent Duplicates in String II" : "remove-all-adjacent-duplicates-in-string-ii",
"Unique Number of Occurrences" : "unique-number-of-occurrences",
"Fizz Buzz Multithreaded" : "fizz-buzz-multithreaded",
"Sort Items by Groups Respecting Dependencies" : "sort-items-by-groups-respecting-dependencies",
"Smallest String With Swaps" : "smallest-string-with-swaps",
"Ugly Number III" : "ugly-number-iii",
"Minimum Absolute Difference" : "minimum-absolute-difference",
"Reformat Department Table" : "reformat-department-table",
"Critical Connections in a Network" : "critical-connections-in-a-network",
"K-Concatenation Maximum Sum" : "k-concatenation-maximum-sum",
"Reverse Substrings Between Each Pair of Parentheses" : "reverse-substrings-between-each-pair-of-parentheses",
"Maximum Number of Balloons" : "maximum-number-of-balloons",
"Make Array Strictly Increasing" : "make-array-strictly-increasing",
"Day of the Week" : "day-of-the-week",
"Maximum Subarray Sum with One Deletion" : "maximum-subarray-sum-with-one-deletion",
"Distance Between Bus Stops" : "distance-between-bus-stops",
"Balance a Binary Search Tree" : "balance-a-binary-search-tree",
"Four Divisors" : "four-divisors",
"Number of Valid Words for Each Puzzle" : "number-of-valid-words-for-each-puzzle",
"Can Make Palindrome from Substring" : "can-make-palindrome-from-substring",
"Prime Arrangements" : "prime-arrangements",
"Largest Multiple of Three" : "largest-multiple-of-three",
"Closest Divisors" : "closest-divisors",
"Validate Binary Tree Nodes" : "validate-binary-tree-nodes",
"Number of Days Between Two Dates" : "number-of-days-between-two-dates",
"Compare Strings by Frequency of the Smallest Character" : "compare-strings-by-frequency-of-the-smallest-character",
"Invalid Transactions" : "invalid-transactions",
"Dinner Plate Stacks" : "dinner-plate-stacks",
"Remove Zero Sum Consecutive Nodes from Linked List" : "remove-zero-sum-consecutive-nodes-from-linked-list",
"Number of Dice Rolls With Target Sum" : "number-of-dice-rolls-with-target-sum",
"Online Majority Element In Subarray" : "online-majority-element-in-subarray",
"Swap For Longest Repeated Character Substring" : "swap-for-longest-repeated-character-substring",
"Day of the Year" : "day-of-the-year",
"Rank Transform of an Array" : "rank-transform-of-an-array",
"Reverse Subarray To Maximize Array Value" : "reverse-subarray-to-maximize-array-value",
"Deepest Leaves Sum" : "deepest-leaves-sum",
"Sort the Matrix Diagonally" : "sort-the-matrix-diagonally",
"Break a Palindrome" : "break-a-palindrome",
"Longest Chunked Palindrome Decomposition" : "longest-chunked-palindrome-decomposition",
"Longest Common Subsequence" : "longest-common-subsequence",
"Snapshot Array" : "snapshot-array",
"Binary Tree Coloring Game" : "binary-tree-coloring-game",
"Decrease Elements To Make Array Zigzag" : "decrease-elements-to-make-array-zigzag",
"Distinct Echo Substrings" : "distinct-echo-substrings",
"Sum of Nodes with Even-Valued Grandparent" : "sum-of-nodes-with-even-valued-grandparent",
"Matrix Block Sum" : "matrix-block-sum",
"Decompress Run-Length Encoded List" : "decompress-run-length-encoded-list",
"Stone Game II" : "stone-game-ii",
"Largest 1-Bordered Square" : "largest-1-bordered-square",
"Alphabet Board Path" : "alphabet-board-path",
"N-th Tribonacci Number" : "n-th-tribonacci-number",
"Number of Paths with Max Score" : "number-of-paths-with-max-score",
"Sum of Mutated Array Closest to Target" : "sum-of-mutated-array-closest-to-target",
"Replace Elements with Greatest Element on Right Side" : "replace-elements-with-greatest-element-on-right-side",
"Maximum of Absolute Value Expression" : "maximum-of-absolute-value-expression",
"Shortest Path with Alternating Colors" : "shortest-path-with-alternating-colors",
"Minimum Cost Tree From Leaf Values" : "minimum-cost-tree-from-leaf-values",
"Number of Equivalent Domino Pairs" : "number-of-equivalent-domino-pairs",
"Minimum Falling Path Sum II" : "minimum-falling-path-sum-ii",
"Remove Covered Intervals" : "remove-covered-intervals",
"Element Appearing More Than 25% In Sorted Array" : "element-appearing-more-than-25-in-sorted-array",
"Smallest Sufficient Team" : "smallest-sufficient-team",
"Longest Well-Performing Interval" : "longest-well-performing-interval",
"Lowest Common Ancestor of Deepest Leaves" : "lowest-common-ancestor-of-deepest-leaves",
"Relative Sort Array" : "relative-sort-array",
"Print Zero Even Odd" : "print-zero-even-odd",
"Sequential Digits" : "sequential-digits",
"Iterator for Combination" : "iterator-for-combination",
"Maximum Nesting Depth of Two Valid Parentheses Strings" : "maximum-nesting-depth-of-two-valid-parentheses-strings",
"Delete Nodes And Return Forest" : "delete-nodes-and-return-forest",
"Corporate Flight Bookings" : "corporate-flight-bookings",
"Defanging an IP Address" : "defanging-an-ip-address",
"Print in Order" : "print-in-order",
"Parsing A Boolean Expression" : "parsing-a-boolean-expression",
"Filling Bookcase Shelves" : "filling-bookcase-shelves",
"Distribute Candies to People" : "distribute-candies-to-people",
"Path In Zigzag Labelled Binary Tree" : "path-in-zigzag-labelled-binary-tree",
"Brace Expansion II" : "brace-expansion-ii",
"Print FooBar Alternately" : "print-foobar-alternately",
"Building H2O" : "building-h2o",
"Find in Mountain Array" : "find-in-mountain-array",
"Car Pooling" : "car-pooling",
"Statistics from a Large Sample" : "statistics-from-a-large-sample",
"Shortest Path in Binary Matrix" : "shortest-path-in-binary-matrix",
"Shortest Common Supersequence " : "shortest-common-supersequence",
"Largest Values From Labels" : "largest-values-from-labels",
"Duplicate Zeros" : "duplicate-zeros",
"Letter Tile Possibilities" : "letter-tile-possibilities",
"Smallest Subsequence of Distinct Characters" : "smallest-subsequence-of-distinct-characters",
"Insufficient Nodes in Root to Leaf Paths" : "insufficient-nodes-in-root-to-leaf-paths",
"Occurrences After Bigram" : "occurrences-after-bigram",
"Adding Two Negabinary Numbers" : "adding-two-negabinary-numbers",
"Flip Columns For Maximum Number of Equal Rows" : "flip-columns-for-maximum-number-of-equal-rows",
"Greatest Common Divisor of Strings" : "greatest-common-divisor-of-strings",
"Number of Submatrices That Sum to Target" : "number-of-submatrices-that-sum-to-target",
"Distant Barcodes" : "distant-barcodes",
"Previous Permutation With One Swap" : "previous-permutation-with-one-swap",
"Grumpy Bookstore Owner" : "grumpy-bookstore-owner",
"Height Checker" : "height-checker",
"Last Substring in Lexicographical Order" : "last-substring-in-lexicographical-order",
"Last Stone Weight II" : "last-stone-weight-ii",
"Longest String Chain" : "longest-string-chain",
"Remove All Adjacent Duplicates In String" : "remove-all-adjacent-duplicates-in-string",
"Last Stone Weight" : "last-stone-weight",
"Longest Duplicate Substring" : "longest-duplicate-substring",
"Partition Array for Maximum Sum" : "partition-array-for-maximum-sum",
"Flower Planting With No Adjacent" : "flower-planting-with-no-adjacent",
"Robot Bounded In Circle" : "robot-bounded-in-circle",
"As Far from Land as Possible" : "as-far-from-land-as-possible",
"Maximum Level Sum of a Binary Tree" : "maximum-level-sum-of-a-binary-tree",
"Valid Boomerang" : "valid-boomerang",
"Binary Search Tree to Greater Sum Tree" : "binary-search-tree-to-greater-sum-tree",
"Moving Stones Until Consecutive II" : "moving-stones-until-consecutive-ii",
"Find Words That Can Be Formed by Characters" : "find-words-that-can-be-formed-by-characters",
"Minimum Score Triangulation of Polygon" : "minimum-score-triangulation-of-polygon",
"Escape a Large Maze" : "escape-a-large-maze",
"Uncrossed Lines" : "uncrossed-lines",
"Coloring A Border" : "coloring-a-border",
"Moving Stones Until Consecutive" : "moving-stones-until-consecutive",
"Stream of Characters" : "stream-of-characters",
"Maximum Sum of Two Non-Overlapping Subarrays" : "maximum-sum-of-two-non-overlapping-subarrays",
"Two City Scheduling" : "two-city-scheduling",
"Matrix Cells in Distance Order" : "matrix-cells-in-distance-order",
"Recover a Tree From Preorder Traversal" : "recover-a-tree-from-preorder-traversal",
"Maximum Difference Between Node and Ancestor" : "maximum-difference-between-node-and-ancestor",
"Longest Arithmetic Sequence" : "longest-arithmetic-sequence",
"Divisor Game" : "divisor-game",
"Video Stitching" : "video-stitching",
"Camelcase Matching" : "camelcase-matching",
"Sum of Root To Leaf Binary Numbers" : "sum-of-root-to-leaf-binary-numbers",
"Remove Outermost Parentheses" : "remove-outermost-parentheses",
"Number of Enclaves" : "number-of-enclaves",
"Next Greater Node In Linked List" : "next-greater-node-in-linked-list",
"Binary Prefix Divisible By 5" : "binary-prefix-divisible-by-5",
"Convert to Base -2" : "convert-to-base-2",
"Binary String With Substrings Representing 1 To N" : "binary-string-with-substrings-representing-1-to-n",
"Smallest Integer Divisible by K" : "smallest-integer-divisible-by-k",
"Best Sightseeing Pair" : "best-sightseeing-pair",
"Partition Array Into Three Parts With Equal Sum" : "partition-array-into-three-parts-with-equal-sum",
"Numbers With Repeated Digits" : "numbers-with-repeated-digits",
"Capacity To Ship Packages Within D Days" : "capacity-to-ship-packages-within-d-days",
"Pairs of Songs With Total Durations Divisible by 60" : "pairs-of-songs-with-total-durations-divisible-by-60",
"Complement of Base 10 Integer" : "complement-of-base-10-integer",
"Construct Binary Search Tree from Preorder Traversal" : "construct-binary-search-tree-from-preorder-traversal",
"Minimum Domino Rotations For Equal Row" : "minimum-domino-rotations-for-equal-row",
"Clumsy Factorial" : "clumsy-factorial",
"Maximize Sum Of Array After K Negations" : "maximize-sum-of-array-after-k-negations",
"Max Consecutive Ones III" : "max-consecutive-ones-iii",
"Check If Word Is Valid After Substitutions" : "check-if-word-is-valid-after-substitutions",
"Find Common Characters" : "find-common-characters",
"Grid Illumination" : "grid-illumination",
"Minimum Cost to Merge Stones" : "minimum-cost-to-merge-stones",
"Available Captures for Rook" : "available-captures-for-rook",
"Maximum Binary Tree II" : "maximum-binary-tree-ii",
"Find the Town Judge" : "find-the-town-judge",
"Number of Squareful Arrays" : "number-of-squareful-arrays",
"Minimum Number of K Consecutive Bit Flips" : "minimum-number-of-k-consecutive-bit-flips",
"Rotting Oranges" : "rotting-oranges",
"Cousins in Binary Tree" : "cousins-in-binary-tree",
"Subarrays with K Different Integers" : "subarrays-with-k-different-integers",
"Broken Calculator" : "broken-calculator",
"Satisfiability of Equality Equations" : "satisfiability-of-equality-equations",
"Add to Array-Form of Integer" : "add-to-array-form-of-integer",
"Smallest String Starting From Leaf" : "smallest-string-starting-from-leaf",
"Vertical Order Traversal of a Binary Tree" : "vertical-order-traversal-of-a-binary-tree",
"Interval List Intersections" : "interval-list-intersections",
"Sum of Even Numbers After Queries" : "sum-of-even-numbers-after-queries",
"String Without AAA or BBB" : "string-without-aaa-or-bbb",
"Minimum Cost For Tickets" : "minimum-cost-for-tickets",
"Triples with Bitwise AND Equal To Zero" : "triples-with-bitwise-and-equal-to-zero",
"Time Based Key-Value Store" : "time-based-key-value-store",
"Unique Paths III" : "unique-paths-iii",
"Distribute Coins in Binary Tree" : "distribute-coins-in-binary-tree",
"Longest Turbulent Subarray" : "longest-turbulent-subarray",
"Squares of a Sorted Array" : "squares-of-a-sorted-array",
"Largest Perimeter Triangle" : "largest-perimeter-triangle",
"Odd Even Jump" : "odd-even-jump",
"Subarray Sums Divisible by K" : "subarray-sums-divisible-by-k",
"K Closest Points to Origin" : "k-closest-points-to-origin",
"Fibonacci Number" : "fibonacci-number",
"Equal Rational Numbers" : "equal-rational-numbers",
"Flip Binary Tree To Match Preorder Traversal" : "flip-binary-tree-to-match-preorder-traversal",
"Powerful Integers" : "powerful-integers",
"Pancake Sorting" : "pancake-sorting",
"Binary Tree Cameras" : "binary-tree-cameras",
"Numbers With Same Consecutive Differences" : "numbers-with-same-consecutive-differences",
"Vowel Spellchecker" : "vowel-spellchecker",
"Univalued Binary Tree" : "univalued-binary-tree",
"Least Operators to Express Number" : "least-operators-to-express-number",
"Minimum Area Rectangle II" : "minimum-area-rectangle-ii",
"Maximum Width Ramp" : "maximum-width-ramp",
"N-Repeated Element in Size 2N Array" : "n-repeated-element-in-size-2n-array",
"Delete Columns to Make Sorted III" : "delete-columns-to-make-sorted-iii",
"Regions Cut By Slashes" : "regions-cut-by-slashes",
"Check Completeness of a Binary Tree" : "check-completeness-of-a-binary-tree",
"Prison Cells After N Days" : "prison-cells-after-n-days",
"Tallest Billboard" : "tallest-billboard",
"Delete Columns to Make Sorted II" : "delete-columns-to-make-sorted-ii",
"Array of Doubled Pairs" : "array-of-doubled-pairs",
"Verifying an Alien Dictionary" : "verifying-an-alien-dictionary",
"Largest Component Size by Common Factor" : "largest-component-size-by-common-factor",
"Flip Equivalent Binary Trees" : "flip-equivalent-binary-trees",
"Reveal Cards In Increasing Order" : "reveal-cards-in-increasing-order",
"Largest Time for Given Digits" : "largest-time-for-given-digits",
"Bag of Tokens" : "bag-of-tokens",
"Most Stones Removed with Same Row or Column" : "most-stones-removed-with-same-row-or-column",
"Validate Stack Sequences" : "validate-stack-sequences",
"Minimum Increment to Make Array Unique" : "minimum-increment-to-make-array-unique",
"Delete Columns to Make Sorted" : "delete-columns-to-make-sorted",
"Find the Shortest Superstring" : "find-the-shortest-superstring",
"DI String Match" : "di-string-match",
"Valid Mountain Array" : "valid-mountain-array",
"Distinct Subsequences II" : "distinct-subsequences-ii",
"Minimum Area Rectangle" : "minimum-area-rectangle",
"Range Sum of BST" : "range-sum-of-bst",
"Reorder Data in Log Files" : "reorder-data-in-log-files",
"Stamping The Sequence" : "stamping-the-sequence",
"Knight Dialer" : "knight-dialer",
"Shortest Bridge" : "shortest-bridge",
"Number of Recent Calls" : "number-of-recent-calls",
"Beautiful Array" : "beautiful-array",
"Minimum Falling Path Sum" : "minimum-falling-path-sum",
"Binary Subarrays With Sum" : "binary-subarrays-with-sum",
"Unique Email Addresses" : "unique-email-addresses",
"Minimize Malware Spread II" : "minimize-malware-spread-ii",
"Three Equal Parts" : "three-equal-parts",
"Flip String to Monotone Increasing" : "flip-string-to-monotone-increasing",
"Long Pressed Name" : "long-pressed-name",
"Minimize Malware Spread" : "minimize-malware-spread",
"3Sum With Multiplicity" : "3sum-with-multiplicity",
"Sort Array By Parity II" : "sort-array-by-parity-ii",
"Minimum Add to Make Parentheses Valid" : "minimum-add-to-make-parentheses-valid",
"Number of Music Playlists" : "number-of-music-playlists",
"Complete Binary Tree Inserter" : "complete-binary-tree-inserter",
"Maximum Sum Circular Subarray" : "maximum-sum-circular-subarray",
"Reverse Only Letters" : "reverse-only-letters",
"Word Subsets" : "word-subsets",
"Partition Array into Disjoint Intervals" : "partition-array-into-disjoint-intervals",
"X of a Kind in a Deck of Cards" : "x-of-a-kind-in-a-deck-of-cards",
"Cat and Mouse" : "cat-and-mouse",
"Sort an Array" : "sort-an-array",
"Online Election" : "online-election",
"Smallest Range II" : "smallest-range-ii",
"Snakes and Ladders" : "snakes-and-ladders",
"Smallest Range I" : "smallest-range-i",
"Sum of Subarray Minimums" : "sum-of-subarray-minimums",
"Super Palindromes" : "super-palindromes",
"Sort Array By Parity" : "sort-array-by-parity",
"Fruit Into Baskets" : "fruit-into-baskets",
"Valid Permutations for DI Sequence" : "valid-permutations-for-di-sequence",
"Numbers At Most N Given Digit Set" : "numbers-at-most-n-given-digit-set",
"Online Stock Span" : "online-stock-span",
"RLE Iterator" : "rle-iterator",
"Orderly Queue" : "orderly-queue",
"Bitwise ORs of Subarrays" : "bitwise-ors-of-subarrays",
"Increasing Order Search Tree" : "increasing-order-search-tree",
"Monotonic Array" : "monotonic-array",
"Maximum Frequency Stack" : "maximum-frequency-stack",
"All Possible Full Binary Trees" : "all-possible-full-binary-trees",
"Groups of Special-Equivalent Strings" : "groups-of-special-equivalent-strings",
"Surface Area of 3D Shapes" : "surface-area-of-3d-shapes",
"Sum of Subsequence Widths" : "sum-of-subsequence-widths",
"Find and Replace Pattern" : "find-and-replace-pattern",
"Construct Binary Tree from Preorder and Postorder Traversal" : "construct-binary-tree-from-preorder-and-postorder-traversal",
"Fair Candy Swap" : "fair-candy-swap",
"Super Egg Drop" : "super-egg-drop",
"Possible Bipartition" : "possible-bipartition",
"Spiral Matrix III" : "spiral-matrix-iii",
"Uncommon Words from Two Sentences" : "uncommon-words-from-two-sentences",
"Projection Area of 3D Shapes" : "projection-area-of-3d-shapes",
"Reachable Nodes In Subdivided Graph" : "reachable-nodes-in-subdivided-graph",
"Boats to Save People" : "boats-to-save-people",
"Decoded String at Index" : "decoded-string-at-index",
"Generate Random Point in a Circle" : "generate-random-point-in-a-circle",
"Random Point in Non-overlapping Rectangles" : "random-point-in-non-overlapping-rectangles",
"Random Flip Matrix" : "random-flip-matrix",
"Random Pick with Weight" : "random-pick-with-weight",
"Profitable Schemes" : "profitable-schemes",
"Nth Magical Number" : "nth-magical-number",
"Stone Game" : "stone-game",
"Middle of the Linked List" : "middle-of-the-linked-list",
"Koko Eating Bananas" : "koko-eating-bananas",
"Walking Robot Simulation" : "walking-robot-simulation",
"Length of Longest Fibonacci Subsequence" : "length-of-longest-fibonacci-subsequence",
"Leaf-Similar Trees" : "leaf-similar-trees",
"Implement Rand10() Using Rand7()" : "implement-rand10-using-rand7",
"Minimum Number of Refueling Stops" : "minimum-number-of-refueling-stops",
"Advantage Shuffle" : "advantage-shuffle",
"Reordered Power of 2" : "reordered-power-of-2",
"Binary Gap" : "binary-gap",
"Transpose Matrix" : "transpose-matrix",
"Prime Palindrome" : "prime-palindrome",
"Smallest Subtree with all the Deepest Nodes" : "smallest-subtree-with-all-the-deepest-nodes",
"Shortest Path to Get All Keys" : "shortest-path-to-get-all-keys",
"Random Pick with Blacklist" : "random-pick-with-blacklist",
"All Nodes Distance K in Binary Tree" : "all-nodes-distance-k-in-binary-tree",
"Shortest Subarray with Sum at Least K" : "shortest-subarray-with-sum-at-least-k",
"Score After Flipping Matrix" : "score-after-flipping-matrix",
"Lemonade Change" : "lemonade-change",
"Buddy Strings" : "buddy-strings",
"Mirror Reflection" : "mirror-reflection",
"Minimum Cost to Hire K Workers" : "minimum-cost-to-hire-k-workers",
"Score of Parentheses" : "score-of-parentheses",
"Exam Room" : "exam-room",
"K-Similar Strings" : "k-similar-strings",
"Car Fleet" : "car-fleet",
"Peak Index in a Mountain Array" : "peak-index-in-a-mountain-array",
"Loud and Rich" : "loud-and-rich",
"Rectangle Area II" : "rectangle-area-ii",
"Maximize Distance to Closest Person" : "maximize-distance-to-closest-person",
"Shifting Letters" : "shifting-letters",
"Shortest Path Visiting All Nodes" : "shortest-path-visiting-all-nodes",
"Hand of Straights" : "hand-of-straights",
"Longest Mountain in Array" : "longest-mountain-in-array",
"Backspace String Compare" : "backspace-string-compare",
"Guess the Word" : "guess-the-word",
"Split Array into Fibonacci Sequence" : "split-array-into-fibonacci-sequence",
"Keys and Rooms" : "keys-and-rooms",
"Magic Squares In Grid" : "magic-squares-in-grid",
"Similar String Groups" : "similar-string-groups",
"Push Dominoes" : "push-dominoes",
"New 21 Game" : "new-21-game",
"Rectangle Overlap" : "rectangle-overlap",
"Image Overlap" : "image-overlap",
"Sum of Distances in Tree" : "sum-of-distances-in-tree",
"Find And Replace in String" : "find-and-replace-in-string",
"Flipping an Image" : "flipping-an-image",
"Design Circular Queue" : "design-circular-queue",
"Design Circular Deque" : "design-circular-deque",
"Masking Personal Information" : "masking-personal-information",
"Positions of Large Groups" : "positions-of-large-groups",
"Consecutive Numbers Sum" : "consecutive-numbers-sum",
"Count Unique Characters of All Substrings of a Given String" : "count-unique-characters-of-all-substrings-of-a-given-string",
"Making A Large Island" : "making-a-large-island",
"Most Profit Assigning Work" : "most-profit-assigning-work",
"Friends Of Appropriate Ages" : "friends-of-appropriate-ages",
"Goat Latin" : "goat-latin",
"Binary Trees With Factors" : "binary-trees-with-factors",
"Card Flipping Game" : "card-flipping-game",
"Shortest Distance to a Character" : "shortest-distance-to-a-character",
"Short Encoding of Words" : "short-encoding-of-words",
"Design Linked List" : "design-linked-list",
"Most Common Word" : "most-common-word",
"Race Car" : "race-car",
"Linked List Components" : "linked-list-components",
"Ambiguous Coordinates" : "ambiguous-coordinates",
"Bus Routes" : "bus-routes",
"Binary Tree Pruning" : "binary-tree-pruning",
"Largest Sum of Averages" : "largest-sum-of-averages",
"Largest Triangle Area" : "largest-triangle-area",
"Subdomain Visit Count" : "subdomain-visit-count",
"Chalkboard XOR Game" : "chalkboard-xor-game",
"Expressive Words" : "expressive-words",
"Soup Servings" : "soup-servings",
"Max Increase to Keep City Skyline" : "max-increase-to-keep-city-skyline",
"Number of Lines To Write String" : "number-of-lines-to-write-string",
"Split Array With Same Average" : "split-array-with-same-average",
"Unique Morse Code Words" : "unique-morse-code-words",
"Bricks Falling When Hit" : "bricks-falling-when-hit",
"Find Eventual Safe States" : "find-eventual-safe-states",
"Minimum Swaps To Make Sequences Increasing" : "minimum-swaps-to-make-sequences-increasing",
"Design Hashmap" : "design-hashmap",
"Design Hashset" : "design-hashset",
"Champagne Tower" : "champagne-tower",
"Smallest Rotation with Highest Score" : "smallest-rotation-with-highest-score",
"All Paths From Source to Target" : "all-paths-from-source-to-target",
"Rotate String" : "rotate-string",
"Number of Subarrays with Bounded Maximum" : "number-of-subarrays-with-bounded-maximum",
"Valid Tic-Tac-Toe State" : "valid-tic-tac-toe-state",
"Preimage Size of Factorial Zeroes Function" : "preimage-size-of-factorial-zeroes-function",
"Number of Matching Subsequences" : "number-of-matching-subsequences",
"Custom Sort String" : "custom-sort-string",
"Domino and Tromino Tiling" : "domino-and-tromino-tiling",
"Escape The Ghosts" : "escape-the-ghosts",
"Rotated Digits" : "rotated-digits",
"Cheapest Flights Within K Stops" : "cheapest-flights-within-k-stops",
"K-th Smallest Prime Fraction" : "k-th-smallest-prime-fraction",
"Is Graph Bipartite?" : "is-graph-bipartite",
"Letter Case Permutation" : "letter-case-permutation",
"Minimum Distance Between BST Nodes" : "minimum-distance-between-bst-nodes",
"Transform to Chessboard" : "transform-to-chessboard",
"Rabbits in Forest" : "rabbits-in-forest",
"Reaching Points" : "reaching-points",
"K-th Symbol in Grammar" : "k-th-symbol-in-grammar",
"Swim in Rising Water" : "swim-in-rising-water",
"Swap Adjacent in LR String" : "swap-adjacent-in-lr-string",
"Binary Search" : "binary-search",
"Global and Local Inversions" : "global-and-local-inversions",
"Kth Largest Element in a Stream" : "kth-largest-element-in-a-stream",
"Sliding Puzzle" : "sliding-puzzle",
"Insert into a Binary Search Tree" : "insert-into-a-binary-search-tree",
"Search in a Binary Search Tree" : "search-in-a-binary-search-tree",
"Jewels and Stones" : "jewels-and-stones",
"Basic Calculator IV" : "basic-calculator-iv",
"Max Chunks To Make Sorted" : "max-chunks-to-make-sorted",
"Max Chunks To Make Sorted II" : "max-chunks-to-make-sorted-ii",
"Reorganize String" : "reorganize-string",
"Toeplitz Matrix" : "toeplitz-matrix",
"N-ary Tree Postorder Traversal" : "n-ary-tree-postorder-traversal",
"N-ary Tree Preorder Traversal" : "n-ary-tree-preorder-traversal",
"Maximum Depth of N-ary Tree" : "maximum-depth-of-n-ary-tree",
"Logical OR of Two Binary Grids Represented as Quad-Trees" : "logical-or-of-two-binary-grids-represented-as-quad-trees",
"Construct Quad Tree" : "construct-quad-tree",
"Couples Holding Hands" : "couples-holding-hands",
"Largest Plus Sign" : "largest-plus-sign",
"Partition Labels" : "partition-labels",
"Prime Number of Set Bits in Binary Representation" : "prime-number-of-set-bits-in-binary-representation",
"Flatten a Multilevel Doubly Linked List" : "flatten-a-multilevel-doubly-linked-list",
"N-ary Tree Level Order Traversal" : "n-ary-tree-level-order-traversal",
"Special Binary String" : "special-binary-string",
"Set Intersection Size At Least Two" : "set-intersection-size-at-least-two",
"Pyramid Transition Matrix" : "pyramid-transition-matrix",
"Reach a Number" : "reach-a-number",
"Cracking the Safe" : "cracking-the-safe",
"Open the Lock" : "open-the-lock",
"Contain Virus" : "contain-virus",
"Shortest Completing Word" : "shortest-completing-word",
"Largest Number At Least Twice of Others" : "largest-number-at-least-twice-of-others",
"Min Cost Climbing Stairs" : "min-cost-climbing-stairs",
"Prefix and Suffix Search" : "prefix-and-suffix-search",
"Find Smallest Letter Greater Than Target" : "find-smallest-letter-greater-than-target",
"Network Delay Time" : "network-delay-time",
"To Lower Case" : "to-lower-case",
"Cherry Pickup" : "cherry-pickup",
"Delete and Earn" : "delete-and-earn",
"Daily Temperatures" : "daily-temperatures",
"Monotone Increasing Digits" : "monotone-increasing-digits",
"Parse Lisp Expression" : "parse-lisp-expression",
"Asteroid Collision" : "asteroid-collision",
"Flood Fill" : "flood-fill",
"My Calendar III" : "my-calendar-iii",
"My Calendar II" : "my-calendar-ii",
"Count Different Palindromic Subsequences" : "count-different-palindromic-subsequences",
"My Calendar I" : "my-calendar-i",
"Self Dividing Numbers" : "self-dividing-numbers",
"Number of Atoms" : "number-of-atoms",
"Split Linked List in Parts" : "split-linked-list-in-parts",
"Find Pivot Index" : "find-pivot-index",
"Remove Comments" : "remove-comments",
"Accounts Merge" : "accounts-merge",
"Longest Word in Dictionary" : "longest-word-in-dictionary",
"Find K-th Smallest Pair Distance" : "find-k-th-smallest-pair-distance",
"Maximum Length of Repeated Subarray" : "maximum-length-of-repeated-subarray",
"1-bit and 2-bit Characters" : "1-bit-and-2-bit-characters",
"Range Module" : "range-module",
"Best Time to Buy and Sell Stock with Transaction Fee" : "best-time-to-buy-and-sell-stock-with-transaction-fee",
"Subarray Product Less Than K" : "subarray-product-less-than-k",
"Minimum ASCII Delete Sum for Two Strings" : "minimum-ascii-delete-sum-for-two-strings",
"Falling Squares" : "falling-squares",
"Partition to K Equal Sum Subsets" : "partition-to-k-equal-sum-subsets",
"Degree of an Array" : "degree-of-an-array",
"Count Binary Substrings" : "count-binary-substrings",
"Max Area of Island" : "max-area-of-island",
"Binary Number with Alternating Bits" : "binary-number-with-alternating-bits",
"Top K Frequent Words" : "top-k-frequent-words",
"Stickers to Spell Word" : "stickers-to-spell-word",
"Employee Importance" : "employee-importance",
"Maximum Sum of 3 Non-Overlapping Subarrays" : "maximum-sum-of-3-non-overlapping-subarrays",
"Knight Probability in Chessboard" : "knight-probability-in-chessboard",
"Longest Univalue Path" : "longest-univalue-path",
"Repeated String Match" : "repeated-string-match",
"Redundant Connection II" : "redundant-connection-ii",
"Redundant Connection" : "redundant-connection",
"Baseball Game" : "baseball-game",
"Valid Palindrome II" : "valid-palindrome-ii",
"24 Game" : "24-game",
"Valid Parenthesis String" : "valid-parenthesis-string",
"Map Sum Pairs" : "map-sum-pairs",
"Implement Magic Dictionary" : "implement-magic-dictionary",
"Cut Off Trees for Golf Event" : "cut-off-trees-for-golf-event",
"Longest Continuous Increasing Subsequence" : "longest-continuous-increasing-subsequence",
"Number of Longest Increasing Subsequence" : "number-of-longest-increasing-subsequence",
"Bulb Switcher II" : "bulb-switcher-ii",
"Second Minimum Node In a Binary Tree" : "second-minimum-node-in-a-binary-tree",
"Maximum Swap" : "maximum-swap",
"Trim a Binary Search Tree" : "trim-a-binary-search-tree",
"Kth Smallest Number in Multiplication Table" : "kth-smallest-number-in-multiplication-table",
"Beautiful Arrangement II" : "beautiful-arrangement-ii",
"Non-decreasing Array" : "non-decreasing-array",
"Strange Printer" : "strange-printer",
"Maximum Width of Binary Tree" : "maximum-width-of-binary-tree",
"Image Smoother" : "image-smoother",
"Split Array into Consecutive Subsequences" : "split-array-into-consecutive-subsequences",
"Find K Closest Elements" : "find-k-closest-elements",
"Robot Return to Origin" : "robot-return-to-origin",
"Print Binary Tree" : "print-binary-tree",
"Maximum Binary Tree" : "maximum-binary-tree",
"Two Sum IV - Input is a BST" : "two-sum-iv-input-is-a-bst",
"Find Duplicate Subtrees" : "find-duplicate-subtrees",
"2 Keys Keyboard" : "2-keys-keyboard",
"Dota2 Senate" : "dota2-senate",
"Replace Words" : "replace-words",
"Palindromic Substrings" : "palindromic-substrings",
"Maximum Length of Pair Chain" : "maximum-length-of-pair-chain",
"Set Mismatch" : "set-mismatch",
"Maximum Average Subarray I" : "maximum-average-subarray-i",
"Solve the Equation" : "solve-the-equation",
"Decode Ways II" : "decode-ways-ii",
"Shopping Offers" : "shopping-offers",
"Average of Levels in Binary Tree" : "average-of-levels-in-binary-tree",
"Exclusive Time of Functions" : "exclusive-time-of-functions",
"Sum of Square Numbers" : "sum-of-square-numbers",
"Smallest Range Covering Elements from K Lists" : "smallest-range-covering-elements-from-k-lists",
"Course Schedule III" : "course-schedule-iii",
"K Inverse Pairs Array" : "k-inverse-pairs-array",
"Maximum Product of Three Numbers" : "maximum-product-of-three-numbers",
"Swap Salary" : "swap-salary",
"Exchange Seats" : "exchange-seats",
"Add One Row to Tree" : "add-one-row-to-tree",
"Task Scheduler" : "task-scheduler",
"Not Boring Movies" : "not-boring-movies",
"Merge Two Binary Trees" : "merge-two-binary-trees",
"Valid Triangle Number" : "valid-triangle-number",
"Find Duplicate File in System" : "find-duplicate-file-in-system",
"Construct String from Binary Tree" : "construct-string-from-binary-tree",
"Can Place Flowers" : "can-place-flowers",
"Human Traffic of Stadium" : "human-traffic-of-stadium",
"Non-negative Integers without Consecutive Ones" : "non-negative-integers-without-consecutive-ones",
"Minimum Index Sum of Two Lists" : "minimum-index-sum-of-two-lists",
"Range Addition II" : "range-addition-ii",
"Classes More Than 5 Students" : "classes-more-than-5-students",
"Big Countries" : "big-countries",
"Longest Harmonious Subsequence" : "longest-harmonious-subsequence",
"Valid Square" : "valid-square",
"Fraction Addition and Subtraction" : "fraction-addition-and-subtraction",
"Tag Validator" : "tag-validator",
"Erect the Fence" : "erect-the-fence",
"Delete Operation for Two Strings" : "delete-operation-for-two-strings",
"Shortest Unsorted Continuous Subarray" : "shortest-unsorted-continuous-subarray",
"Out of Boundary Paths" : "out-of-boundary-paths",
"Distribute Candies" : "distribute-candies",
"Subtree of Another Tree" : "subtree-of-another-tree",
"Permutation in String" : "permutation-in-string",
"Reshape the Matrix" : "reshape-the-matrix",
"Array Nesting" : "array-nesting",
"Find the Closest Palindrome" : "find-the-closest-palindrome",
"Binary Tree Tilt" : "binary-tree-tilt",
"Array Partition I" : "array-partition-i",
"Subarray Sum Equals K" : "subarray-sum-equals-k",
"Reverse Words in a String III" : "reverse-words-in-a-string-iii",
"Next Greater Element III" : "next-greater-element-iii",
"Brick Wall" : "brick-wall",
"Optimal Division" : "optimal-division",
"Student Attendance Record II" : "student-attendance-record-ii",
"Student Attendance Record I" : "student-attendance-record-i",
"Friend Circles" : "friend-circles",
"Remove Boxes" : "remove-boxes",
"Diameter of Binary Tree" : "diameter-of-binary-tree",
"01 Matrix" : "01-matrix",
"Reverse String II" : "reverse-string-ii",
"Single Element in a Sorted Array" : "single-element-in-a-sorted-array",
"Minimum Time Difference" : "minimum-time-difference",
"Convert BST to Greater Tree" : "convert-bst-to-greater-tree",
"Complex Number Multiplication" : "complex-number-multiplication",
"Encode and Decode TinyURL" : "encode-and-decode-tinyurl",
"K-diff Pairs in an Array" : "k-diff-pairs-in-an-array",
"Minimum Absolute Difference in BST" : "minimum-absolute-difference-in-bst",
"Minesweeper" : "minesweeper",
"Beautiful Arrangement" : "beautiful-arrangement",
"Contiguous Array" : "contiguous-array",
"Longest Word in Dictionary through Deleting" : "longest-word-in-dictionary-through-deleting",
"Continuous Subarray Sum" : "continuous-subarray-sum",
"Longest Uncommon Subsequence II" : "longest-uncommon-subsequence-ii",
"Longest Uncommon Subsequence I " : "longest-uncommon-subsequence-i",
"Detect Capital" : "detect-capital",
"Coin Change 2" : "coin-change-2",
"Super Washing Machines" : "super-washing-machines",
"Longest Palindromic Subsequence" : "longest-palindromic-subsequence",
"Find Largest Value in Each Tree Row" : "find-largest-value-in-each-tree-row",
"Freedom Trail" : "freedom-trail",
"Find Bottom Left Tree Value" : "find-bottom-left-tree-value",
"Most Frequent Subtree Sum" : "most-frequent-subtree-sum",
"Perfect Number" : "perfect-number",
"Relative Ranks" : "relative-ranks",
"Base 7" : "base-7",
"Next Greater Element II" : "next-greater-element-ii",
"IPO" : "ipo",
"Find Mode in Binary Search Tree" : "find-mode-in-binary-search-tree",
"Keyboard Row" : "keyboard-row",
"Diagonal Traverse" : "diagonal-traverse",
"Next Greater Element I" : "next-greater-element-i",
"Teemo Attacking" : "teemo-attacking",
"Target Sum" : "target-sum",
"Reverse Pairs" : "reverse-pairs",
"Construct the Rectangle" : "construct-the-rectangle",
"Increasing Subsequences" : "increasing-subsequences",
"Zuma Game" : "zuma-game",
"Predict the Winner" : "predict-the-winner",
"Max Consecutive Ones" : "max-consecutive-ones",
"Smallest Good Base" : "smallest-good-base",
"License Key Formatting" : "license-key-formatting",
"Magical String" : "magical-string",
"Sliding Window Median" : "sliding-window-median",
"Largest Palindrome Product" : "largest-palindrome-product",
"Total Hamming Distance" : "total-hamming-distance",
"Number Complement" : "number-complement",
"Heaters" : "heaters",
"Ones and Zeroes" : "ones-and-zeroes",
"Matchsticks to Square" : "matchsticks-to-square",
"Concatenated Words" : "concatenated-words",
"Validate IP Address" : "validate-ip-address",
"Unique Substrings in Wraparound String" : "unique-substrings-in-wraparound-string",
"Count The Repetitions" : "count-the-repetitions",
"Can I Win" : "can-i-win",
"Island Perimeter" : "island-perimeter",
"Minimum Moves to Equal Array Elements II" : "minimum-moves-to-equal-array-elements-ii",
"Hamming Distance" : "hamming-distance",
"LFU Cache" : "lfu-cache",
"Repeated Substring Pattern" : "repeated-substring-pattern",
"Poor Pigs" : "poor-pigs",
"Circular Array Loop" : "circular-array-loop",
"132 Pattern" : "132-pattern",
"Assign Cookies" : "assign-cookies",
"4Sum II" : "4sum-ii",
"Minimum Moves to Equal Array Elements" : "minimum-moves-to-equal-array-elements",
"Minimum Number of Arrows to Burst Balloons" : "minimum-number-of-arrows-to-burst-balloons",
"Sort Characters By Frequency" : "sort-characters-by-frequency",
"Delete Node in a BST" : "delete-node-in-a-bst",
"Serialize and Deserialize BST" : "serialize-and-deserialize-bst",
"Find All Numbers Disappeared in an Array" : "find-all-numbers-disappeared-in-an-array",
"Number of Boomerangs" : "number-of-boomerangs",
"Arithmetic Slices II - Subsequence" : "arithmetic-slices-ii-subsequence",
"Add Two Numbers II" : "add-two-numbers-ii",
"String Compression" : "string-compression",
"Find All Duplicates in an Array" : "find-all-duplicates-in-an-array",
"Arranging Coins" : "arranging-coins",
"K-th Smallest in Lexicographical Order" : "k-th-smallest-in-lexicographical-order",
"Find All Anagrams in a String" : "find-all-anagrams-in-a-string",
"Path Sum III" : "path-sum-iii",
"Find Right Interval" : "find-right-interval",
"Non-overlapping Intervals" : "non-overlapping-intervals",
"Number of Segments in a String" : "number-of-segments-in-a-string",
"Minimum Genetic Mutation" : "minimum-genetic-mutation",
"All O`one Data Structure" : "all-oone-data-structure",
"Longest Repeating Character Replacement" : "longest-repeating-character-replacement",
"Reconstruct Original Digits from English" : "reconstruct-original-digits-from-english",
"Maximum XOR of Two Numbers in an Array" : "maximum-xor-of-two-numbers-in-an-array",
"Strong Password Checker" : "strong-password-checker",
"Battleships in a Board" : "battleships-in-a-board",
"Pacific Atlantic Water Flow" : "pacific-atlantic-water-flow",
"Partition Equal Subset Sum" : "partition-equal-subset-sum",
"Add Strings" : "add-strings",
"Third Maximum Number" : "third-maximum-number",
"Arithmetic Slices" : "arithmetic-slices",
"Fizz Buzz" : "fizz-buzz",
"Split Array Largest Sum" : "split-array-largest-sum",
"Longest Palindrome" : "longest-palindrome",
"Trapping Rain Water II" : "trapping-rain-water-ii",
"Queue Reconstruction by Height" : "queue-reconstruction-by-height",
"Convert a Number to Hexadecimal" : "convert-a-number-to-hexadecimal",
"Sum of Left Leaves" : "sum-of-left-leaves",
"Frog Jump" : "frog-jump",
"Remove K Digits" : "remove-k-digits",
"Binary Watch" : "binary-watch",
"Nth Digit" : "nth-digit",
"Evaluate Division" : "evaluate-division",
"Random Pick Index" : "random-pick-index",
"Integer Replacement" : "integer-replacement",
"Rotate Function" : "rotate-function",
"Longest Substring with At Least K Repeating Characters" : "longest-substring-with-at-least-k-repeating-characters",
"Decode String" : "decode-string",
"UTF-8 Validation" : "utf-8-validation",
"Is Subsequence" : "is-subsequence",
"Perfect Rectangle" : "perfect-rectangle",
"Elimination Game" : "elimination-game",
"Find the Difference" : "find-the-difference",
"Longest Absolute File Path" : "longest-absolute-file-path",
"First Unique Character in a String" : "first-unique-character-in-a-string",
"Lexicographical Numbers" : "lexicographical-numbers",
"Mini Parser" : "mini-parser",
"Shuffle an Array" : "shuffle-an-array",
"Ransom Note" : "ransom-note",
"Linked List Random Node" : "linked-list-random-node",
"Insert Delete GetRandom O(1) - Duplicates allowed" : "insert-delete-getrandom-o1-duplicates-allowed",
"Insert Delete GetRandom O(1)" : "insert-delete-getrandom-o1",
"Kth Smallest Element in a Sorted Matrix" : "kth-smallest-element-in-a-sorted-matrix",
"Combination Sum IV" : "combination-sum-iv",
"Wiggle Subsequence" : "wiggle-subsequence",
"Guess Number Higher or Lower II" : "guess-number-higher-or-lower-ii",
"Guess Number Higher or Lower" : "guess-number-higher-or-lower",
"Find K Pairs with Smallest Sums" : "find-k-pairs-with-smallest-sums",
"Super Pow" : "super-pow",
"Sum of Two Integers" : "sum-of-two-integers",
"Largest Divisible Subset" : "largest-divisible-subset",
"Valid Perfect Square" : "valid-perfect-square",
"Water and Jug Problem" : "water-and-jug-problem",
"Max Sum of Rectangle No Larger Than K" : "max-sum-of-rectangle-no-larger-than-k",
"Count Numbers with Unique Digits" : "count-numbers-with-unique-digits",
"Design Twitter" : "design-twitter",
"Russian Doll Envelopes" : "russian-doll-envelopes",
"Data Stream as Disjoint Intervals" : "data-stream-as-disjoint-intervals",
"Intersection of Two Arrays II" : "intersection-of-two-arrays-ii",
"Intersection of Two Arrays" : "intersection-of-two-arrays",
"Top K Frequent Elements" : "top-k-frequent-elements",
"Reverse Vowels of a String" : "reverse-vowels-of-a-string",
"Reverse String" : "reverse-string",
"Integer Break" : "integer-break",
"Power of Four" : "power-of-four",
"Flatten Nested List Iterator" : "flatten-nested-list-iterator",
"Counting Bits" : "counting-bits",
"House Robber III" : "house-robber-iii",
"Palindrome Pairs" : "palindrome-pairs",
"Self Crossing" : "self-crossing",
"Increasing Triplet Subsequence" : "increasing-triplet-subsequence",
"Reconstruct Itinerary" : "reconstruct-itinerary",
"Verify Preorder Serialization of a Binary Tree" : "verify-preorder-serialization-of-a-binary-tree",
"Patching Array" : "patching-array",
"Longest Increasing Path in a Matrix" : "longest-increasing-path-in-a-matrix",
"Odd Even Linked List" : "odd-even-linked-list",
"Count of Range Sum" : "count-of-range-sum",
"Power of Three" : "power-of-three",
"Wiggle Sort II" : "wiggle-sort-ii",
"Coin Change" : "coin-change",
"Create Maximum Number" : "create-maximum-number",
"Bulb Switcher" : "bulb-switcher",
"Maximum Product of Word Lengths" : "maximum-product-of-word-lengths",
"Remove Duplicate Letters" : "remove-duplicate-letters",
"Count of Smaller Numbers After Self" : "count-of-smaller-numbers-after-self",
"Super Ugly Number" : "super-ugly-number",
"Burst Balloons" : "burst-balloons",
"Minimum Height Trees" : "minimum-height-trees",
"Best Time to Buy and Sell Stock with Cooldown" : "best-time-to-buy-and-sell-stock-with-cooldown",
"Range Sum Query - Mutable" : "range-sum-query-mutable",
"Additive Number" : "additive-number",
"Range Sum Query 2D - Immutable" : "range-sum-query-2d-immutable",
"Range Sum Query - Immutable" : "range-sum-query-immutable",
"Remove Invalid Parentheses" : "remove-invalid-parentheses",
"Longest Increasing Subsequence" : "longest-increasing-subsequence",
"Bulls and Cows" : "bulls-and-cows",
"Serialize and Deserialize Binary Tree" : "serialize-and-deserialize-binary-tree",
"Find Median from Data Stream" : "find-median-from-data-stream",
"Nim Game" : "nim-game",
"Word Pattern" : "word-pattern",
"Game of Life" : "game-of-life",
"Find the Duplicate Number" : "find-the-duplicate-number",
"Peeking Iterator" : "peeking-iterator",
"Move Zeroes" : "move-zeroes",
"Expression Add Operators" : "expression-add-operators",
"Perfect Squares" : "perfect-squares",
"First Bad Version" : "first-bad-version",
"H-Index II" : "h-index-ii",
"H-Index" : "h-index",
"Integer to English Words" : "integer-to-english-words",
"Missing Number" : "missing-number",
"Ugly Number II" : "ugly-number-ii",
"Ugly Number" : "ugly-number",
"Trips and Users" : "trips-and-users",
"Single Number III" : "single-number-iii",
"Add Digits" : "add-digits",
"Binary Tree Paths" : "binary-tree-paths",
"Valid Anagram" : "valid-anagram",
"Different Ways to Add Parentheses" : "different-ways-to-add-parentheses",
"Search a 2D Matrix II" : "search-a-2d-matrix-ii",
"Sliding Window Maximum" : "sliding-window-maximum",
"Product of Array Except Self" : "product-of-array-except-self",
"Delete Node in a Linked List" : "delete-node-in-a-linked-list",
"Lowest Common Ancestor of a Binary Tree" : "lowest-common-ancestor-of-a-binary-tree",
"Lowest Common Ancestor of a Binary Search Tree" : "lowest-common-ancestor-of-a-binary-search-tree",
"Palindrome Linked List" : "palindrome-linked-list",
"Number of Digit One" : "number-of-digit-one",
"Implement Queue using Stacks" : "implement-queue-using-stacks",
"Power of Two" : "power-of-two",
"Kth Smallest Element in a BST" : "kth-smallest-element-in-a-bst",
"Majority Element II" : "majority-element-ii",
"Summary Ranges" : "summary-ranges",
"Basic Calculator II" : "basic-calculator-ii",
"Invert Binary Tree" : "invert-binary-tree",
"Implement Stack using Queues" : "implement-stack-using-queues",
"Basic Calculator" : "basic-calculator",
"Rectangle Area" : "rectangle-area",
"Count Complete Tree Nodes" : "count-complete-tree-nodes",
"Maximal Square" : "maximal-square",
"Contains Duplicate III" : "contains-duplicate-iii",
"Contains Duplicate II" : "contains-duplicate-ii",
"The Skyline Problem" : "the-skyline-problem",
"Contains Duplicate" : "contains-duplicate",
"Combination Sum III" : "combination-sum-iii",
"Kth Largest Element in an Array" : "kth-largest-element-in-an-array",
"Shortest Palindrome" : "shortest-palindrome",
"House Robber II" : "house-robber-ii",
"Word Search II" : "word-search-ii",
"Add and Search Word - Data structure design" : "add-and-search-word-data-structure-design",
"Course Schedule II" : "course-schedule-ii",
"Minimum Size Subarray Sum" : "minimum-size-subarray-sum",
"Implement Trie (Prefix Tree)" : "implement-trie-prefix-tree",
"Course Schedule" : "course-schedule",
"Reverse Linked List" : "reverse-linked-list",
"Isomorphic Strings" : "isomorphic-strings",
"Count Primes" : "count-primes",
"Remove Linked List Elements" : "remove-linked-list-elements",
"Happy Number" : "happy-number",
"Bitwise AND of Numbers Range" : "bitwise-and-of-numbers-range",
"Number of Islands" : "number-of-islands",
"Binary Tree Right Side View" : "binary-tree-right-side-view",
"House Robber" : "house-robber",
"Rising Temperature" : "rising-temperature",
"Delete Duplicate Emails" : "delete-duplicate-emails",
"Tenth Line" : "tenth-line",
"Transpose File" : "transpose-file",
"Valid Phone Numbers" : "valid-phone-numbers",
"Word Frequency" : "word-frequency",
"Number of 1 Bits" : "number-of-1-bits",
"Reverse Bits" : "reverse-bits",
"Rotate Array" : "rotate-array",
"Best Time to Buy and Sell Stock IV" : "best-time-to-buy-and-sell-stock-iv",
"Repeated DNA Sequences" : "repeated-dna-sequences",
"Department Top Three Salaries" : "department-top-three-salaries",
"Department Highest Salary" : "department-highest-salary",
"Customers Who Never Order" : "customers-who-never-order",
"Duplicate Emails" : "duplicate-emails",
"Employees Earning More Than Their Managers" : "employees-earning-more-than-their-managers",
"Consecutive Numbers" : "consecutive-numbers",
"Largest Number" : "largest-number",
"Rank Scores" : "rank-scores",
"Nth Highest Salary" : "nth-highest-salary",
"Second Highest Salary" : "second-highest-salary",
"Combine Two Tables" : "combine-two-tables",
"Dungeon Game" : "dungeon-game",
"Binary Search Tree Iterator" : "binary-search-tree-iterator",
"Factorial Trailing Zeroes" : "factorial-trailing-zeroes",
"Excel Sheet Column Number" : "excel-sheet-column-number",
"Majority Element" : "majority-element",
"Excel Sheet Column Title" : "excel-sheet-column-title",
"Two Sum II - Input array is sorted" : "two-sum-ii-input-array-is-sorted",
"Fraction to Recurring Decimal" : "fraction-to-recurring-decimal",
"Compare Version Numbers" : "compare-version-numbers",
"Maximum Gap" : "maximum-gap",
"Find Peak Element" : "find-peak-element",
"Intersection of Two Linked Lists" : "intersection-of-two-linked-lists",
"Min Stack" : "min-stack",
"Find Minimum in Rotated Sorted Array II" : "find-minimum-in-rotated-sorted-array-ii",
"Find Minimum in Rotated Sorted Array" : "find-minimum-in-rotated-sorted-array",
"Maximum Product Subarray" : "maximum-product-subarray",
"Reverse Words in a String" : "reverse-words-in-a-string",
"Evaluate Reverse Polish Notation" : "evaluate-reverse-polish-notation",
"Max Points on a Line" : "max-points-on-a-line",
"Sort List" : "sort-list",
"Insertion Sort List" : "insertion-sort-list",
"LRU Cache" : "lru-cache",
"Binary Tree Postorder Traversal" : "binary-tree-postorder-traversal",
"Binary Tree Preorder Traversal" : "binary-tree-preorder-traversal",
"Reorder List" : "reorder-list",
"Linked List Cycle II" : "linked-list-cycle-ii",
"Linked List Cycle" : "linked-list-cycle",
"Word Break II" : "word-break-ii",
"Word Break" : "word-break",
"Copy List with Random Pointer" : "copy-list-with-random-pointer",
"Single Number II" : "single-number-ii",
"Single Number" : "single-number",
"Candy" : "candy",
"Gas Station" : "gas-station",
"Clone Graph" : "clone-graph",
"Palindrome Partitioning II" : "palindrome-partitioning-ii",
"Palindrome Partitioning" : "palindrome-partitioning",
"Surrounded Regions" : "surrounded-regions",
"Sum Root to Leaf Numbers" : "sum-root-to-leaf-numbers",
"Longest Consecutive Sequence" : "longest-consecutive-sequence",
"Word Ladder" : "word-ladder",
"Word Ladder II" : "word-ladder-ii",
"Valid Palindrome" : "valid-palindrome",
"Binary Tree Maximum Path Sum" : "binary-tree-maximum-path-sum",
"Best Time to Buy and Sell Stock III" : "best-time-to-buy-and-sell-stock-iii",
"Best Time to Buy and Sell Stock II" : "best-time-to-buy-and-sell-stock-ii",
"Best Time to Buy and Sell Stock" : "best-time-to-buy-and-sell-stock",
"Triangle" : "triangle",
"Pascal's Triangle II" : "pascals-triangle-ii",
"Pascal's Triangle" : "pascals-triangle",
"Populating Next Right Pointers in Each Node II" : "populating-next-right-pointers-in-each-node-ii",
"Populating Next Right Pointers in Each Node" : "populating-next-right-pointers-in-each-node",
"Distinct Subsequences" : "distinct-subsequences",
"Flatten Binary Tree to Linked List" : "flatten-binary-tree-to-linked-list",
"Path Sum II" : "path-sum-ii",
"Path Sum" : "path-sum",
"Minimum Depth of Binary Tree" : "minimum-depth-of-binary-tree",
"Balanced Binary Tree" : "balanced-binary-tree",
"Convert Sorted List to Binary Search Tree" : "convert-sorted-list-to-binary-search-tree",
"Convert Sorted Array to Binary Search Tree" : "convert-sorted-array-to-binary-search-tree",
"Binary Tree Level Order Traversal II" : "binary-tree-level-order-traversal-ii",
"Construct Binary Tree from Inorder and Postorder Traversal" : "construct-binary-tree-from-inorder-and-postorder-traversal",
"Construct Binary Tree from Preorder and Inorder Traversal" : "construct-binary-tree-from-preorder-and-inorder-traversal",
"Maximum Depth of Binary Tree" : "maximum-depth-of-binary-tree",
"Binary Tree Zigzag Level Order Traversal" : "binary-tree-zigzag-level-order-traversal",
"Binary Tree Level Order Traversal" : "binary-tree-level-order-traversal",
"Symmetric Tree" : "symmetric-tree",
"Same Tree" : "same-tree",
"Recover Binary Search Tree" : "recover-binary-search-tree",
"Validate Binary Search Tree" : "validate-binary-search-tree",
"Interleaving String" : "interleaving-string",
"Unique Binary Search Trees" : "unique-binary-search-trees",
"Unique Binary Search Trees II" : "unique-binary-search-trees-ii",
"Binary Tree Inorder Traversal" : "binary-tree-inorder-traversal",
"Restore IP Addresses" : "restore-ip-addresses",
"Reverse Linked List II" : "reverse-linked-list-ii",
"Decode Ways" : "decode-ways",
"Subsets II" : "subsets-ii",
"Gray Code" : "gray-code",
"Merge Sorted Array" : "merge-sorted-array",
"Scramble String" : "scramble-string",
"Partition List" : "partition-list",
"Maximal Rectangle" : "maximal-rectangle",
"Largest Rectangle in Histogram" : "largest-rectangle-in-histogram",
"Remove Duplicates from Sorted List" : "remove-duplicates-from-sorted-list",
"Remove Duplicates from Sorted List II" : "remove-duplicates-from-sorted-list-ii",
"Search in Rotated Sorted Array II" : "search-in-rotated-sorted-array-ii",
"Remove Duplicates from Sorted Array II" : "remove-duplicates-from-sorted-array-ii",
"Word Search" : "word-search",
"Subsets" : "subsets",
"Combinations" : "combinations",
"Minimum Window Substring" : "minimum-window-substring",
"Sort Colors" : "sort-colors",
"Search a 2D Matrix" : "search-a-2d-matrix",
"Set Matrix Zeroes" : "set-matrix-zeroes",
"Edit Distance" : "edit-distance",
"Simplify Path" : "simplify-path",
"Climbing Stairs" : "climbing-stairs",
"Sqrt(x)" : "sqrtx",
"Text Justification" : "text-justification",
"Add Binary" : "add-binary",
"Plus One" : "plus-one",
"Valid Number" : "valid-number",
"Minimum Path Sum" : "minimum-path-sum",
"Unique Paths II" : "unique-paths-ii",
"Unique Paths" : "unique-paths",
"Rotate List" : "rotate-list",
"Permutation Sequence" : "permutation-sequence",
"Spiral Matrix II" : "spiral-matrix-ii",
"Length of Last Word" : "length-of-last-word",
"Insert Interval" : "insert-interval",
"Merge Intervals" : "merge-intervals",
"Jump Game" : "jump-game",
"Spiral Matrix" : "spiral-matrix",
"Maximum Subarray" : "maximum-subarray",
"N-Queens II" : "n-queens-ii",
"N-Queens" : "n-queens",
"Pow(x, n)" : "powx-n",
"Group Anagrams" : "group-anagrams",
"Rotate Image" : "rotate-image",
"Permutations II" : "permutations-ii",
"Permutations" : "permutations",
"Jump Game II" : "jump-game-ii",
"Wildcard Matching" : "wildcard-matching",
"Multiply Strings" : "multiply-strings",
"Trapping Rain Water" : "trapping-rain-water",
"First Missing Positive" : "first-missing-positive",
"Combination Sum II" : "combination-sum-ii",
"Combination Sum" : "combination-sum",
"Count and Say" : "count-and-say",
"Sudoku Solver" : "sudoku-solver",
"Valid Sudoku" : "valid-sudoku",
"Search Insert Position" : "search-insert-position",
"Find First and Last Position of Element in Sorted Array" : "find-first-and-last-position-of-element-in-sorted-array",
"Search in Rotated Sorted Array" : "search-in-rotated-sorted-array",
"Longest Valid Parentheses" : "longest-valid-parentheses",
"Next Permutation" : "next-permutation",
"Substring with Concatenation of All Words" : "substring-with-concatenation-of-all-words",
"Divide Two Integers" : "divide-two-integers",
"Implement strStr()" : "implement-strstr",
"Remove Element" : "remove-element",
"Remove Duplicates from Sorted Array" : "remove-duplicates-from-sorted-array",
"Reverse Nodes in k-Group" : "reverse-nodes-in-k-group",
"Swap Nodes in Pairs" : "swap-nodes-in-pairs",
"Merge k Sorted Lists" : "merge-k-sorted-lists",
"Generate Parentheses" : "generate-parentheses",
"Merge Two Sorted Lists" : "merge-two-sorted-lists",
"Valid Parentheses" : "valid-parentheses",
"Remove Nth Node From End of List" : "remove-nth-node-from-end-of-list",
"4Sum" : "4sum",
"Letter Combinations of a Phone Number" : "letter-combinations-of-a-phone-number",
"3Sum Closest" : "3sum-closest",
"3Sum" : "3sum",
"Longest Common Prefix" : "longest-common-prefix",
"Roman to Integer" : "roman-to-integer",
"Integer to Roman" : "integer-to-roman",
"Container With Most Water" : "container-with-most-water",
"Regular Expression Matching" : "regular-expression-matching",
"Palindrome Number" : "palindrome-number",
"String to Integer (atoi)" : "string-to-integer-atoi",
"Reverse Integer" : "reverse-integer",
"ZigZag Conversion" : "zigzag-conversion",
"Longest Palindromic Substring" : "longest-palindromic-substring",
"Median of Two Sorted Arrays" : "median-of-two-sorted-arrays",
"Longest Substring Without Repeating Characters" : "longest-substring-without-repeating-characters",
"Add Two Numbers" : "add-two-numbers",
"Two Sum" : "two-sum"
}

head = "| **Topic**                                   | **Difficulty** |                                                              |\n"
layout = "| :-------------------------------------- | :--------: | :----------------------------------------------------------: |\n"